//Creae User
POST http://localhost:5000/user
Content-Type: application/json

{
    "name":"Nadhifa Hasna Amira",
    "email":"difa@gmail.com",
    "password":"sukses",
    "confPassword":"sukses",
    "role":"user"
}

###
GET http://localhost:5000/users

###
GET http://localhost:5000/user/605a7525-8491-474f-8f48-390e3f7aa34d

###
PATCH  http://localhost:5000/user/605a7525-8491-474f-8f48-390e3f7aa34d
###
PATCH  http://localhost:5000/user/605a7525-8491-474f-8f48-390e3f7aa34d
Content-Type: application/json

{
    "name":"Elan Z",
    "email":"elan@gmail.com",
    "password":"sukses",
    "confPassword":"sukses",
    "role":"admin"
}
###
DELETE   http://localhost:5000/users/7ca6fb59-b28c-40a8-a24d-e4f559b3f12c
Content-Type: application/json

###
//Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"elan@gmail.com",
    "password":"sukses"   
}

//ME
###
GET http://localhost:5000/me
###
//Logout
DELETE http://localhost:5000/logout




###
//getALL Kategori
GET http://localhost:5000/kategoris
###
//get Single Katgegori
GET http://localhost:5000/kategori/b6188291-48b4-4e04-8561-5e5f9241f194
###
//Create Product
POST http://localhost:5000/product
Content-Type: application/json

{
    "kode":"P001",
    "nama":"Nasi Goreng",
    "harga":15000,
    "is_ready":true,
    "gambar":"gmbar.jpg",
    "kategoriId":1
    
}


###
//Update Kategori
PATCH http://localhost:5000/kategori/79eeee49-c0e3-45ec-814c-dac095f526ef
Content-Type: application/json

{
    "nama":"makanan u"
    
}

###

DELETE http://localhost:5000/kategori/79eeee49-c0e3-45ec-814c-dac095f526ef


###
POST http://localhost:5000/kategori
Content-Type: application/json

{
    "nama":"Disert"
}