//Creae User
POST http://localhost:5000/user
Content-Type: application/json

{
    "name":"Elan Z",
    "email":"elan@gmail.com",
    "password":"sukses",
    "confPassword":"sukses",
    "role":"admin"
}

###
GET http://localhost:5000/user

###
GET http://localhost:5000/user/605a7525-8491-474f-8f48-390e3f7aa34d

###
PATCH  http://localhost:5000/users/605a7525-8491-474f-8f48-390e3f7aa34d
###
PATCH  http://localhost:5000/user/605a7525-8491-474f-8f48-390e3f7aa34d
Content-Type: application/json

{
    "name":"Elan Zaelani",
    "email":"elan@gmail.com",
    "password":"",
    "confPassword":"",
    "role":"admin"
}
###
DELETE   http://localhost:5000/users/7ca6fb59-b28c-40a8-a24d-e4f559b3f12c
Content-Type: application/json

